// Dapps Incorporated 2020. All Rights Reserved.

public class AccountWrapper {
        @InvocableVariable(label='AccountId')
        public Id AccountId;
        @InvocableVariable(label='AccountName')
        public String AccountName;
        @InvocableVariable(label='AccountType')
        public String AccountType;
        @InvocableVariable(label='PhoneNumber')
        public String PhoneNumber;
        @InvocableVariable(label='Industry')
        public String Industry;
    	@InvocableVariable(label='Owner')
    	public Id Owner;
        
    }