// Dapps Incorporated 2020. All Rights Reserved.

public class UserWrapper {

    @InvocableVariable(label='UserId')
    public Id UserId;
    @InvocableVariable(label='OrgId')
	public Id OrgId;
    @InvocableVariable(label='FirstName')
    public String FirstName;
    @InvocableVariable(label='LastName')
   	public String LastName;
    @InvocableVariable(label='Email')
    public String Email;
    @InvocableVariable(label='Title')
    public String Title;
    @InvocableVariable(label='Organization')
    public String Company;
        
}